<?php


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-31 at 01:52:54.
 */
class Mumsys_ContextTest extends PHPUnit_Framework_TestCase
{


    /**
     * @var Mumsys_Context
     */
    protected $_object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_version = '1.0.2';
        $this->_logfile = '/tmp/'.basename(__FILE__) . '.log';
        $this->_object = new Mumsys_Context();
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        @unlink($this->_logfile);
    }


//    /**
//     * @covers Mumsys_Context::getConfig
//     * @todo   Implement testGetConfig().
//     */
//    public function testGetConfig()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::setConfig
//     * @todo   Implement testSetConfig().
//     */
//    public function testSetConfig()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::getPermissions
//     * @todo   Implement testGetPermissions().
//     */
//    public function testGetPermissions()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::setPermissions
//     * @todo   Implement testSetPermissions().
//     */
//    public function testSetPermissions()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }


    /**
     * @covers Mumsys_Context::getSession
     * @covers Mumsys_Context::registerSession
     * @covers Mumsys_Context::_get
     * @covers Mumsys_Context::_register
     */
    public function testGetSetSession()
    {
        $session = new Mumsys_Session();
        $this->_object->registerSession($session);

        $this->assertInstanceOf('Mumsys_Session', $this->_object->getSession());

        $this->setExpectedException('Mumsys_Exception', 'already');
        $this->_object->registerSession($session);
    }

//
//    /**
//     * @covers Mumsys_Context::getDatabase
//     * @todo   Implement testGetDatabase().
//     */
//    public function testGetDatabase()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::setDatabase
//     * @todo   Implement testSetDatabase().
//     */
//    public function testSetDatabase()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::getControllerBackend
//     * @todo   Implement testGetControllerBackend().
//     */
//    public function testGetControllerBackend()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::setControllerBackend
//     * @todo   Implement testSetControllerBackend().
//     */
//    public function testSetControllerBackend()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::getDisplay
//     * @todo   Implement testGetDisplay().
//     */
//    public function testGetDisplay()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::setDisplay
//     * @todo   Implement testSetDisplay().
//     */
//    public function testSetDisplay()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::replaceDisplay
//     * @todo   Implement testReplaceDisplay().
//     */
//    public function testReplaceDisplay()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::getTranslation
//     * @todo   Implement testGetTranslation().
//     */
//    public function testGetTranslation()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::setTranslation
//     * @todo   Implement testSetTranslation().
//     */
//    public function testSetTranslation()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }


    /**
     * @covers Mumsys_Context::getLogger
     * @covers Mumsys_Context::setLogger
     * @covers Mumsys_Context::_get
     * @covers Mumsys_Context::_register
     */
    public function testGetSetLogger()
    {
        $logger = new Mumsys_Logger(array('logfile' => $this->_logfile));
        $this->_object->setLogger($logger);

        $this->assertInstanceOf('Mumsys_Logger_Interface', $this->_object->getLogger());
    }

//
//    /**
//     * @covers Mumsys_Context::getControllerFrontend
//     * @todo   Implement testGetControllerFrontend().
//     */
//    public function testGetControllerFrontend()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }
//
//
//    /**
//     * @covers Mumsys_Context::setControllerFrontend
//     * @todo   Implement testSetControllerFrontend().
//     */
//    public function testSetControllerFrontend()
//    {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//            'This test has not been implemented yet.'
//        );
//    }

    // test abstracts


    /**
     * @covers Mumsys_Context::getVersion
     */
    public function testGetVersion()
    {
        $this->assertEquals('Mumsys_Context ' . $this->_version, $this->_object->getVersion());
    }


    /**
     * @covers Mumsys_Context::getVersionID
     */
    public function testgetVersionID()
    {
        $this->assertEquals($this->_version, $this->_object->getVersionID());
    }


    /**
     * @covers Mumsys_Context::getVersions
     */
    public function testgetVersions()
    {
        $expected = array(
            'Mumsys_Abstract' => '3.0.1',
            'Mumsys_Context' => $this->_version,
        );

        $possible = $this->_object->getVersions();

        foreach ($expected as $must => $value) {
            $this->assertTrue(isset($possible[$must]));
            $this->assertTrue(($possible[$must] == $value));
        }
    }

}
