<?php


/**
 * Mumsys_Weather_Item_Unit_Factory Test
 * Generated by PHPUnit_SkeletonGenerator on 2018-01-21 at 16:22:08.
 */
class Mumsys_Weather_Item_Unit_FactoryTest
    extends Mumsys_Unittest_Testcase
{
    /**
     * @var Mumsys_Weather_Item_Unit_Factory
     */
    protected $_object;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_object = new Mumsys_Weather_Item_Unit_Factory;
    }


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->_object = null;
    }


    /**
     * @covers Mumsys_Weather_Item_Unit_Factory::createItem
     */
    public function testCreateItem()
    {
        $actual = $this->_object->createItem();

        $this->assertInstanceOf( 'Mumsys_Weather_Item_Unit_Interface', $actual );
        $this->assertInstanceOf( 'Mumsys_Weather_Item_Unit_Default', $actual );

        $this->expectException( 'Mumsys_Weather_Exception' );
        $mesg = 'Invalid characters in class name "Mumsys_Weather_Item_Unit_$$$"';
        $this->expectExceptionMessage( $mesg );
        $this->_object->createItem( '$$$' );
    }


    /**
     * @covers Mumsys_Weather_Item_Unit_Factory::createItem
     */
    public function testCreateItemException()
    {
        $this->expectException( 'Mumsys_Weather_Exception' );
        $mesg = 'Class "Mumsys_Weather_Item_Unit_DriverNotIn" not found';
        $this->expectExceptionMessage( $mesg );
        $actual = $this->_object->createItem( 'DriverNotIn' );
    }

}
